#!/bin/bash
# Distributed under the terms of the GNU General Public License v2

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source "${SCRIPTPATH}"/_util/isolated-functions.sh || exit 1

if [[ $# -lt 1 ]] ; then
	__helpers_die "${0##*/}: kernel-file not specified"
	exit 1
fi

install -D -m0644 -o 0 -g 0 "${1}" "${KERNEL"
echo "${1}" >> "${KERNEL_MODULES_DIR}/firmware.extra-files"


for fn in `find "${KERNEL_MODULES_DIR}" -name '*.ko'` ; do
	modinfo ${fn} | while read -r line ; do
		fw=`echo ${line} | sed -nr 's/firmware: +(\\S.*)/\1/p'`       # $fw is a wildcard string
		if [[ "${fw}" != "" && "${2}" == ${fw} ]] ; then
			install -D -m0644 -o 0 -g 0 "${1}" "${FIRMWARE_DIR}/${2}"
		fi
	done
done
