#!/bin/bash
# Distributed under the terms of the GNU General Public License v2

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

source "${SCRIPTPATH}"/_util/isolated-functions.sh || exit 1

if [[ $# -lt 1 ]] ; then
	__helpers_die "${0##*/}: src-file not specified"
	exit 1
fi

if [[ $# -lt 2 ]] ; then
	__helpers_die "${0##*/}: dst-dir not specified"
	exit 1
fi

install -D -m0644 -o 0 -g 0 -t "${2}" "${1}"
