#!/bin/bash
# Distributed under the terms of the GNU General Public License v2

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

source "${SCRIPTPATH}"/_util/isolated-functions.sh || exit 1

if [[ $# -lt 1 ]] ; then
	__helpers_die "${0##*/}: src-file not specified"
	exit 1
fi

if [[ $# -lt 2 ]] ; then
	__helpers_die "${0##*/}: firmware-file not specified"
	exit 1
fi

for fn in `find /lib/modules/${KVER} -name '*.ko'`; do
	modinfo ${fn} | while read -r line; do
		fw=`echo ${line} | sed -n 's/firmware: +(\\S.*)/\1/p'`
		if [ "${fw}" -eq "${2}" ] ; then
			install -D -m0644 -o 0 -g 0 "${1}" "/lib/firmware/${2}"
		fi
	done
done
