#!/bin/bash
# Distributed under the terms of the GNU General Public License v2

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

source "${SCRIPTPATH}"/_util/isolated-functions.sh || exit 1

if [[ $# -lt 1 ]] ; then
	__helpers_die "${0##*/}: src-file not specified"
	exit 1
fi

install -D -m0644 -o 0 -g 0 "${1}" "${FIRMWARE_DIR}/${1}"
echo "${1}" >> "${KERNEL_MODULES_DIR}/firmware.extra-files"
